name: healthlife
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.de
version: 1.0.0+1

environment:
  sdk: ^3.10.7
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  firebase_storage: ^13.2.0
  firebase_messaging: ^16.1.2

  # State management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Router
  go_router: ^15.1.2

  # Local storage
  shared_preferences: ^2.3.4

  # UI helpers
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  lottie: ^3.3.3
  timezone: ^0.11.1
  intl: ^0.20.2
  shimmer: ^3.0.0
  # RSS
  webfeed_revised: ^0.9.0
  
  # WebView
  webview_flutter: ^4.14.1
  # HTTP (đọc RSS)
  http: ^1.6.0
  #Languages
  easy_localization: ^3.0.7
  gap: ^3.0.1
  google_sign_in: ^7.2.0
  liquid_glass_renderer: ^0.2.0-dev.4
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  hive_ce_generator: ^1.4.0
  flutter_gen_runner: ^5.15.0

flutter_gen:
  output: lib/generated/
  line_length: 80
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/intro/
    - assets/svg/
    - assets/png/
    - assets/translations/
    - assets/data/ 

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_28pt-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter_28pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter_28pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_28pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_28pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter_28pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter_28pt-Black.ttf
          weight: 900