// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWxDQ0EI56WdjbpTq6Oi3_xtr9rREdQ_w',
    appId: '1:265215699847:android:a0a57f05de3b4c42a9c122',
    messagingSenderId: '265215699847',
    projectId: 'healthlife-e89fd',
    storageBucket: 'healthlife-e89fd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo_bW0Qly2pdZxO0iBO4zilt56HwD4EhM',
    appId: '1:265215699847:ios:4ec50cc843744c2aa9c122',
    messagingSenderId: '265215699847',
    projectId: 'healthlife-e89fd',
    storageBucket: 'healthlife-e89fd.firebasestorage.app',
    androidClientId: '265215699847-4h40avpoq09f9rb2bnf02vfda4io40tl.apps.googleusercontent.com',
    iosClientId: '265215699847-nemtgs4cugted5nmsh3f9ogtt4tug9da.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthlife',
  );
}
